name: CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  byte-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: '29.4'

      - name: Byte-compile
        run: |
          emacs --batch -L . \
            --eval "(setq byte-compile-error-on-warn t)" \
            -f batch-byte-compile feynman-chiron.el
